import './globals.css'
import {Roboto_Flex} from 'next/font/google'
import {ThemeProvider} from "@/app/theme-provider";
import 'grapesjs/dist/css/grapes.min.css';
import 'swiper/css';

const robotoFlex = Roboto_Flex({subsets: ['greek'], variable: '--font-roboto'})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">

        <body className={`${robotoFlex.variable} font-sans`}>
        <ThemeProvider>
            {children}
        </ThemeProvider>
        </body>
        </html>
    )
}
